/**
 * Polish UI copy — single source for user-visible strings.
 * Import in Astro frontmatter or React components; no runtime i18n layer in v1.
 */
export const pl = {
  appName: "Mój Ogród",
  appTagline: "Zarządzaj polami, pogodą i siewem w jednym miejscu",

  nav: {
    dashboard: "Panel",
    catalog: "Katalog",
    plantRequests: "Zgłoś roślinę",
    settings: "Ustawienia",
    admin: "Admin",
    signIn: "Zaloguj się",
    signUp: "Załóż konto",
    signOut: "Wyloguj się",
    notSignedIn: "Niezalogowany",
  },

  landing: {
    headline: "Twój ogród pod kontrolą",
    subhead: "Planuj pola, śledź pogodę i zapisuj siewy — prosto, z telefonu.",
    featureFieldsTitle: "Pola uprawne",
    featureFieldsDesc: "Twórz siatki pól i oznaczaj co posadziłeś w każdej komórce.",
    featureWeatherTitle: "Pogoda w regionie",
    featureWeatherDesc: "Sprawdzaj opady i temperaturę dla swojej lokalizacji.",
    featurePlantingTitle: "Śledzenie siewu",
    featurePlantingDesc: "Zapisuj daty siewu i szacuj zbiór na podstawie katalogu roślin.",
    ctaSignIn: "Zaloguj się",
    ctaSignUp: "Załóż konto",
  },

  auth: {
    signInTitle: "Zaloguj się",
    signUpTitle: "Załóż konto",
    confirmEmailTitle: "Potwierdź e-mail",
    confirmEmailMessage: "Sprawdź skrzynkę i kliknij link aktywacyjny, aby dokończyć rejestrację.",
    confirmEmailBack: "Wróć do logowania",
    confirmEmailDevTitle: "Rejestracja zakończona",
    confirmEmailDevMessage: "Konto zostało utworzone. Możesz się teraz zalogować.",
    confirmEmailDevLink: "Przejdź do logowania",
    emailLabel: "E-mail",
    emailPlaceholder: "twoj@email.pl",
    passwordLabel: "Hasło",
    passwordPlaceholder: "Twoje hasło",
    passwordMinPlaceholder: "Min. 6 znaków",
    confirmPasswordLabel: "Potwierdź hasło",
    confirmPasswordPlaceholder: "Powtórz hasło",
    signInButton: "Zaloguj się",
    signInPending: "Logowanie…",
    signUpButton: "Utwórz konto",
    signUpPending: "Tworzenie konta…",
    noAccount: "Nie masz konta?",
    hasAccount: "Masz już konto?",
    linkSignUp: "Załóż konto",
    linkSignIn: "Zaloguj się",
    errors: {
      emailRequired: "E-mail jest wymagany",
      emailInvalid: "Podaj prawidłowy adres e-mail",
      passwordRequired: "Hasło jest wymagane",
      passwordMinLength: (min: number) => `Hasło musi mieć co najmniej ${min} znaków`,
      confirmPasswordRequired: "Potwierdź hasło",
      passwordsMismatch: "Hasła nie są identyczne",
      passwordCharsNeeded: (count: number) =>
        count === 1 ? "Potrzebny jeszcze 1 znak" : `Potrzebne jeszcze ${count} znaki`,
    },
  },

  dashboard: {
    title: "Panel",
    myFields: "Moje pola",
    newField: "Nowe pole",
    noFields: "Nie masz jeszcze żadnych pól.",
    createFirstField: "Utwórz pierwsze pole →",
    rowsCols: (rows: number, cols: number) => `${rows} rzędów × ${cols} kolumn`,
    locationNotSet: "Ustaw lokalizację ogrodu w ustawieniach, aby zobaczyć pogodę i tworzyć pola.",
    locationRequiredBeforeField: "Wybierz lokalizację ogrodu w ustawieniach, zanim utworzysz pole.",
    goToSettings: "Przejdź do ustawień",
  },

  catalog: {
    title: "Katalog roślin",
    subtitle: "Przeglądaj dostępne gatunki w systemie.",
    growthDays: "Dni wzrostu",
    wateringNeeds: "Potrzeby wodne",
    wateringLow: "Niskie",
    wateringMedium: "Średnie",
    wateringHigh: "Wysokie",
    empty: "Brak roślin w katalogu.",
    requestLink: "Nie ma Twojej rośliny? Zgłoś ją →",
  },

  plantRequests: {
    title: "Zgłoś roślinę",
    subtitle: "Zaproponuj nowy gatunek do katalogu. Administrator zatwierdzi wpis.",
    formLabel: "Nazwa rośliny",
    formPlaceholder: "np. Bazylia genowska",
    submit: "Wyślij zgłoszenie",
    submitPending: "Wysyłanie…",
    success: "Zgłoszenie zostało wysłane.",
    empty: "Nie masz oczekujących zgłoszeń.",
    pendingHeading: "Twoje oczekujące zgłoszenia",
    statusPending: "Oczekuje",
    errors: {
      nameRequired: "Nazwa jest wymagana",
      nameMinLength: "Nazwa musi mieć co najmniej 2 znaki",
      submitFailed: "Nie udało się wysłać zgłoszenia.",
    },
  },

  settings: {
    title: "Ustawienia",
    profileHeading: "Profil",
    emailLabel: "E-mail",
    locationHeading: "Lokalizacja",
    locationDescription: "Używana do prognozy pogody w Twoim regionie.",
    currentCity: "Aktualne miasto",
    changeCity: "Zmień miasto",
    signOutHeading: "Sesja",
    signOutDescription: "Wyloguj się z tego urządzenia.",
  },

  fields: {
    newTitle: "Nowe pole",
    detailTitle: (name: string) => name,
    nameLabel: "Nazwa pola",
    namePlaceholder: "np. Główny grządka warzywna",
    colsLabel: "Kolumny (szerokość)",
    rowsLabel: "Rzędy (wysokość)",
    regionLabel: "Region",
    regionPlaceholder: "Wybierz region…",
    regionSearch: "Szukaj regionów…",
    createButton: "Utwórz pole",
    createPending: "Tworzenie…",
    backToDashboard: "← Wróć do panelu",
    plantingTitle: "Zasadzenie",
    plantingAddTitle: "Nowe zasadzenie",
    plantingEditTitle: "Edytuj zasadzenie",
    catalogSelectLabel: "Wybierz z katalogu",
    catalogEmpty: "Brak roślin w katalogu — wpisz nazwę poniżej.",
    plantManualLabel: "Lub wpisz nazwę ręcznie",
    plantLabel: "Roślina",
    plantPlaceholder: "Wybierz roślinę…",
    plantSearch: "Szukaj roślin…",
    plantButton: "Zasadź",
    updatePlanting: "Aktualizuj",
    deleteConfirmButton: "Potwierdź usunięcie",
    unknownPlant: "Nieznana",
    seedingDateLabel: "Data siewu",
    notesLabel: "Notatki",
    notesPlaceholder: "Opcjonalne notatki…",
    savePlanting: "Zapisz",
    savePending: "Zapisywanie…",
    deletePlanting: "Usuń zasadzenie",
    deleteConfirm: "Czy na pewno usunąć to zasadzenie?",
    harvestEstimate: "Szacowany zbiór",
    emptyCell: "Puste",
    errors: {
      general: "Coś poszło nie tak",
      network: "Błąd sieci. Spróbuj ponownie.",
    },
  },

  weather: {
    title: "Pogoda",
    searchPlaceholder: "Wpisz miasto…",
    noResults: "Brak wyników",
    loading: "Ładowanie pogody…",
    stale: "Dane mogą być nieaktualne",
    fetchError: "Nie udało się pobrać danych pogodowych.",
    rainfall: "Opady",
    lastRain: "Ostatni deszcz",
    lastRainNoData: "Brak danych",
    relativeToday: "dzisiaj",
    relativeYesterday: "wczoraj",
    relativeDaysAgo: (days: number) => `${days} dni temu`,
    searchPrompt: "Wyszukaj miasto, aby zobaczyć pogodę.",
    temperature: "Temperatura",
    humidity: "Wilgotność",
    wind: "Wiatr",
    conditions: {
      clear: "Bezchmurnie",
      cloudy: "Pochmurno",
      rain: "Deszcz",
      snow: "Śnieg",
      fog: "Mgła",
      unknown: "Nieznane",
    },
  },

  admin: {
    title: "Zgłoszenia roślin",
    subtitle: "Zatwierdź oczekujące rośliny do katalogu lub odrzuć je.",
    empty: "Brak oczekujących zgłoszeń.",
    approve: "Zatwierdź",
    approvePending: "Zatwierdzanie…",
    reject: "Odrzuć",
    rejectPending: "Odrzucanie…",
    rejectConfirm: "Usunąć to zgłoszenie?",
    rejectConfirmDescription: "Tej operacji nie można cofnąć. Zgłoszenie zostanie trwale usunięte.",
    approveDialogTitle: "Zatwierdź zgłoszenie",
    approveDialogDescription: "Uzupełnij dane katalogowe przed publikacją rośliny.",
    plantNameLabel: "Nazwa rośliny",
    wateringPlaceholder: "niski / średni / wysoki",
    unknownUser: "nieznany",
    created: "Utworzono",
    user: "Użytkownik",
    growthDaysLabel: "Dni wzrostu",
    wateringNeedsLabel: "Potrzeby wodne",
    errors: {
      approveFailed: "Nie udało się zatwierdzić zgłoszenia.",
      rejectFailed: "Nie udało się odrzucić zgłoszenia.",
    },
  },

  common: {
    save: "Zapisz",
    cancel: "Anuluj",
    back: "Wstecz",
    loading: "Ładowanie…",
    notFound: "Nie znaleziono strony",
    notFoundMessage: "Ta strona nie istnieje lub została przeniesiona.",
    goHome: "Strona główna",
    goDashboard: "Przejdź do panelu",
    error: "Wystąpił błąd",
    tryAgain: "Spróbuj ponownie",
  },
} as const;

export type PlCopy = typeof pl;
